services:
  frontend:
    image: node:21-alpine3.18
    build:
      context: ./frontend
    depends_on:
      - database

  backend:
    build:
      context: ./backend
    depends_on:
      - database

  database:
    image: mongo:6
    volumes:
      - db:/data/db

  proxy:
    build: ./proxy
    ports: ['8001:80']
    depends_on:
      - database
      - frontend

volumes:
  db:
