services:
  habits-frontend:
    image: node:21-alpine3.18
    build:
      context: ./frontend
    depends_on:
      - habits-database

  habits-backend:
    build:
      context: ./backend
    depends_on:
      - habits-database

  habits-database:
    image: mongo:6
    volumes:
      - db:/data/db

  habits-proxy:
    build: ./proxy
    ports: ['8001:80']
    depends_on:
      - habits-database
      - habits-frontend

volumes:
  db:
